import React, { useState, useRef, useEffect } from 'react';
import { colors, fonts, spacing, borderRadius, shadows, transitions } from '../../shared/design-tokens';

const DISCLAIMER_KEY = 'podplay-disclaimer-accepted';

interface SimulationDisclaimerProps {
  onAccept: () => void;
}

export const SimulationDisclaimer: React.FC<SimulationDisclaimerProps> = ({ onAccept }) => {
  const [scrolledToBottom, setScrolledToBottom] = useState(false);
  const [dontShowAgain, setDontShowAgain] = useState(false);
  const contentRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    const el = contentRef.current;
    if (!el) return;
    const handleScroll = () => {
      const atBottom = el.scrollHeight - el.scrollTop - el.clientHeight < 20;
      if (atBottom) setScrolledToBottom(true);
    };
    // Check immediately in case content doesn't overflow
    handleScroll();
    el.addEventListener('scroll', handleScroll);
    return () => el.removeEventListener('scroll', handleScroll);
  }, []);

  const handleAccept = () => {
    if (dontShowAgain) {
      try { localStorage.setItem(DISCLAIMER_KEY, 'true'); } catch {}
    }
    onAccept();
  };

  return (
    <div style={s.overlay}>
      <div style={s.modal}>
        <div style={s.header}>
          <div style={s.iconWrap}>
            <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke={colors.warning} strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round">
              <path d="M10.29 3.86L1.82 18a2 2 0 001.71 3h16.94a2 2 0 001.71-3L13.71 3.86a2 2 0 00-3.42 0z" />
              <line x1="12" y1="9" x2="12" y2="13" />
              <line x1="12" y1="17" x2="12.01" y2="17" />
            </svg>
          </div>
          <h2 style={s.title}>Simulation Disclaimer & Terms of Use</h2>
          <p style={s.subtitle}>Please read and scroll to the bottom to continue</p>
        </div>

        <div ref={contentRef} style={s.content}>
          <p style={s.paragraph}>
            <strong style={s.strong}>IMPORTANT NOTICE:</strong> The PodPlay Court Optimizer simulation tool
            ("Simulator") is provided for <strong style={s.strong}>informational and illustrative purposes only</strong>.
            By accessing and using the Simulator, you acknowledge and agree to the following terms:
          </p>

          <h3 style={s.sectionTitle}>Simulation Limitations</h3>
          <p style={s.paragraph}>
            The results generated by the Simulator are based on Monte Carlo simulations that rely on
            statistical modeling, randomized inputs, and simplifying assumptions regarding facility operations,
            booking patterns, customer behavior, and scheduling dynamics. These assumptions may not accurately
            reflect the specific conditions, constraints, or characteristics of your business or facility.
          </p>

          <h3 style={s.sectionTitle}>No Guarantee of Results</h3>
          <p style={s.paragraph}>
            Simulation outputs — including but not limited to projected revenue, utilization rates,
            efficiency metrics, and comparative analyses — are <strong style={s.strong}>estimates derived from
            hypothetical scenarios</strong>. They do not constitute a guarantee, warranty, or representation
            of actual performance. Real-world results may vary materially from simulated outcomes due to
            factors not captured by the model.
          </p>

          <h3 style={s.sectionTitle}>Not Professional Advice</h3>
          <p style={s.paragraph}>
            The Simulator and its outputs do not constitute financial, business, operational, or professional
            advice of any kind. You should not rely solely on simulation results when making business decisions.
            PodPlay recommends consulting with qualified professionals before making operational or financial
            decisions based on any data presented herein.
          </p>

          <h3 style={s.sectionTitle}>Algorithm Subject to Change</h3>
          <p style={s.paragraph}>
            PodPlay reserves the right to modify, update, or replace its scheduling algorithm and optimization
            methodology at any time without prior notice. Any such changes may or may not be reflected in the
            Simulator. The performance characteristics shown in the Simulator may differ from those of the
            production algorithm deployed in PodPlay's commercial products.
          </p>

          <h3 style={s.sectionTitle}>Limitation of Liability</h3>
          <p style={s.paragraph}>
            To the fullest extent permitted by applicable law, PodPlay and its affiliates, officers, directors,
            employees, and agents shall not be liable for any direct, indirect, incidental, consequential, or
            special damages arising out of or in connection with your use of or reliance on the Simulator or
            its outputs, regardless of the cause of action or theory of liability.
          </p>

          <h3 style={s.sectionTitle}>Acceptance of Terms</h3>
          <p style={s.paragraph}>
            By clicking "I Acknowledge & Accept" below, you confirm that you have read, understood, and agree
            to the terms set forth in this disclaimer and that you accept full responsibility for any decisions
            made based on the Simulator's outputs.
          </p>
        </div>

        {!scrolledToBottom && (
          <div style={s.scrollHint}>
            <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke={colors.textMuted} strokeWidth="2">
              <path d="M7 13l5 5 5-5M7 6l5 5 5-5" />
            </svg>
            <span>Scroll down to continue</span>
          </div>
        )}

        <div style={s.footer}>
          <label style={s.checkboxLabel}>
            <input
              type="checkbox"
              checked={dontShowAgain}
              onChange={e => setDontShowAgain(e.target.checked)}
              style={s.checkbox}
            />
            Don't show this again
          </label>
          <button
            style={{
              ...s.acceptBtn,
              ...(scrolledToBottom ? {} : s.acceptBtnDisabled),
            }}
            disabled={!scrolledToBottom}
            onClick={handleAccept}
          >
            I Acknowledge & Accept
          </button>
        </div>
      </div>
    </div>
  );
};

export function hasAcceptedDisclaimer(): boolean {
  try {
    return localStorage.getItem(DISCLAIMER_KEY) === 'true';
  } catch {
    return false;
  }
}

const s: Record<string, React.CSSProperties> = {
  overlay: {
    position: 'fixed',
    inset: 0,
    backgroundColor: colors.overlay,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10000,
    padding: spacing.lg,
  },
  modal: {
    backgroundColor: colors.surface,
    border: `1px solid ${colors.border}`,
    borderRadius: borderRadius.lg,
    maxWidth: '600px',
    width: '100%',
    maxHeight: '85vh',
    display: 'flex',
    flexDirection: 'column',
    boxShadow: shadows.xl,
  },
  header: {
    padding: `${spacing.xl} ${spacing.xl} ${spacing.md}`,
    textAlign: 'center',
    borderBottom: `1px solid ${colors.borderLight}`,
    flexShrink: 0,
  },
  iconWrap: {
    marginBottom: spacing.md,
  },
  title: {
    fontSize: fonts.sizeLg,
    fontWeight: fonts.weightBold,
    color: colors.text,
    margin: 0,
    marginBottom: spacing.sm,
  },
  subtitle: {
    fontSize: fonts.sizeSmall,
    color: colors.textMuted,
    margin: 0,
  },
  content: {
    padding: `${spacing.lg} ${spacing.xl}`,
    overflowY: 'auto',
    flex: 1,
    minHeight: 0,
  },
  sectionTitle: {
    fontSize: fonts.sizeMd,
    fontWeight: fonts.weightSemibold,
    color: colors.accent,
    margin: 0,
    marginTop: spacing.lg,
    marginBottom: spacing.sm,
  },
  paragraph: {
    fontSize: fonts.sizeBase,
    color: colors.textSecondary,
    lineHeight: fonts.lineHeightRelaxed,
    margin: 0,
    marginBottom: spacing.md,
  },
  strong: {
    color: colors.text,
    fontWeight: 400,
  },
  scrollHint: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing.xs,
    padding: spacing.sm,
    fontSize: fonts.sizeSmall,
    color: colors.textMuted,
    borderTop: `1px solid ${colors.borderLight}`,
    flexShrink: 0,
  },
  footer: {
    padding: `${spacing.md} ${spacing.xl} ${spacing.xl}`,
    borderTop: `1px solid ${colors.borderLight}`,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: spacing.md,
    flexShrink: 0,
  },
  checkboxLabel: {
    display: 'flex',
    alignItems: 'center',
    gap: spacing.sm,
    fontSize: fonts.sizeSmall,
    color: colors.textSecondary,
    cursor: 'pointer',
    userSelect: 'none',
  },
  checkbox: {
    width: '16px',
    height: '16px',
    cursor: 'pointer',
  },
  acceptBtn: {
    width: '100%',
    padding: `${spacing.md} ${spacing.xl}`,
    fontSize: fonts.sizeMd,
    fontWeight: fonts.weightSemibold,
    fontFamily: fonts.family,
    color: '#ffffff',
    backgroundColor: colors.primary,
    border: 'none',
    borderRadius: borderRadius.sm,
    cursor: 'pointer',
    transition: `all ${transitions.fast}`,
  },
  acceptBtnDisabled: {
    opacity: 0.4,
    cursor: 'not-allowed',
  },
};
